### ISSUE TITLE
Movie is playing backgroung when trying to go back to full player

### ISSUE THREAD

**Issue by pawlosck** [FreeTubeApp/FreeTube-Vue#151] opened 2020-09-21 23:16 UTC
1. Open movie
2. Go to picture in picture mode
3. Go to other view, for example, try to search for other movie
4. Go back from mini player to full player. Movie is playing background

**Comment by PrestonN** [comment] 2020-09-21 23:20
Duplicate of #126

I'm actually almost done with a fix for this.  Will be fixed soon.

**Closed by PrestonN** 2020-09-21 23:20 UTC

**Comment by pawlosck** [comment] 2020-09-21 23:37
What solution did you selected?
I think, the best solution would be to ask if to go back to movie page and next switch to movie page and switch to normal player

**Comment by PrestonN** [comment] 2020-09-22 01:43
I will not be doing that for now as I'm not adding any new features until after the full release.  I can debate on including it in the future though.

**Comment by pawlosck** [comment] 2020-09-22 12:16
So do you want to report the same issue after the full release?
