### ISSUE TITLE
4K video support

### ISSUE THREAD

**Issue by xeleven11** [FreeTubeApp/FreeTube-Vue#144] opened 2020-09-19 22:48 UTC
Original FreeTube has no problem playing 4K or 60fps videos however Vue has no support at all? Also a lot of subtitles have bugs that plays the previous video's and some won't even display at all even though it's included.

**Comment by PrestonN** [comment] 2020-09-20 01:57
The subtitles is a duplicate of #103.  Please make separate issues in the future.  It's more difficult to track when multiple issues are in one thread.

Your other problem I already addressed in my latest blog post.  There's an upstream issue that's preventing qualities higher than 1080p from playing.  This will not be worked on until some point after the initial release.  Because of that, I will be closing this issue here as we'll be tracking that issue and others back at the main repo once the first release has passed.

**Closed by PrestonN** 2020-09-20 01:57 UTC
