### ISSUE TITLE
Subscribe button show "8,189.999,999,999,999"

### ISSUE THREAD

**Issue by pawlosck** [FreeTubeApp/FreeTube-Vue#160] opened 2020-09-23 19:27 UTC
Open this song in freetube -> https://www.youtube.com/watch?v=F5pywDM0j9E
and look at subscription button. There is info about "8,189.999,999,999,999" subscriptions, but youtube show info about "8,19 tyś" (tyś -> thousand). Look at dots, commas and generally number.

**Comment by PrestonN** [comment] 2020-09-23 19:36
This looks to be an upstream issue with a module that I'm using.  I'll create an issue over there and have them fix it on their end.  I'll link the issue back here once I've created it.

**Comment by PrestonN** [comment] 2020-09-23 19:42
Issue has been created [here](https://github.com/fent/node-ytdl-core/issues/711).  Once it has been patched upstream, I will update my dependencies and the issue should be fixed.

Will be closing now that the appropriate issue has been created.

**Closed by PrestonN** 2020-09-23 19:42 UTC
Labels: bug

**Comment by pawlosck** [comment] 2020-09-23 19:47
Could you tell me what does "upstream issue" mean? You used it a lot of times and I don't know what does it mean.
I tried to translate it, but translation is not make sense.

**Comment by PrestonN** [comment] 2020-09-23 19:57
An "Upstream Issue" is an issue that is caused by something that the "Downstream" project (In this case, FreeTube) depends on.

This means that the problem isn't a problem with FreeTube itself, rather it's an issue with another project that FreeTube depends on.

Once the other project has fixed it, then I can update FreeTube to also provide the fix.

Hope that makes sense.

**Comment by pawlosck** [comment] 2020-09-23 20:00
Yes, that makes sense. Thank you.

**Comment by PrestonN** [comment] 2020-09-25 21:47
This should be fixed now

**Comment by pawlosck** [comment] 2020-09-25 22:06
Not fixed.
Do I have to update something to see correct value?

**Comment by PrestonN** [comment] 2020-09-25 22:14
If you're running in dev, you'll need to update packages.  Run `npm install` to update.

**Comment by pawlosck** [comment] 2020-09-25 22:27
ok, fixed. There was problem with git.
