### ISSUE TITLE
(Debian)The SUID sandbox helper binary was found, but is not configured correctly.

### ISSUE THREAD

**Issue by ShenDemoni** [FreeTubeApp/FreeTube-Vue#56] opened 2020-08-03 01:54 UTC
After installing the .deb file from the site, I tried to launch it through the menu and there was no response, so I ran it through the terminal and got this result:

> [5226:0802/204953.255320:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/FreeTube/chrome-sandbox is owned by root and has mode 4755.
> Trace/breakpoint trap

**Comment by PrestonN** [comment] 2020-08-03 02:16
If you downloaded the app from the official website, then it sounds like you're looking for [this](https://github.com/FreeTubeApp/FreeTube/issues/439) issue.  The repo is for the rewrite that's currently ongoing, where the linked repo is for the live release.

**Comment by d43m0nhLInt3r** [comment] 2020-08-03 04:10
fixed in [electron-builder v.22](https://github.com/electron-userland/electron-builder/releases/tag/v22.0.0)

**Comment by PrestonN** [comment] 2020-08-03 21:17
Since this is related to the old code base (and since the issue is also fixed over there), I will go ahead and close this issue.

**Closed by PrestonN** 2020-08-03 21:17 UTC
